name: Bingo
version: 1.1.1
main: me.danseb.bingo.MainBingo
authors: [DanSeb2000]
description: Bingo!
commands:
  bingo:
    usage: /bingo
    description: Open the bingo board
  start:
    usage: /start
    description: Starts the game
  team:
    usage: /team
    description: Join a team
  setspawn:
    usage: /team
    description: Set spawn
